// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChqMVA4gb2eCRU3jfmN_WMAqg329S36pA',
    appId: '1:267307291692:web:790683d59ebcd7c606ad89',
    messagingSenderId: '267307291692',
    projectId: 'ma-chong',
    authDomain: 'ma-chong.firebaseapp.com',
    storageBucket: 'ma-chong.firebasestorage.app',
    measurementId: 'G-QKD6RV5EJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvl_5-Qig7P4fOMMXPASCjlMvRgAshY-M',
    appId: '1:267307291692:android:4cfe5d5a0dd5c0aa06ad89',
    messagingSenderId: '267307291692',
    projectId: 'ma-chong',
    storageBucket: 'ma-chong.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv1fhV1QelBSXCYPWWkf9YBOwKnVqn28s',
    appId: '1:267307291692:ios:06c09a0cc93c1b1506ad89',
    messagingSenderId: '267307291692',
    projectId: 'ma-chong',
    storageBucket: 'ma-chong.firebasestorage.app',
    iosBundleId: 'com.example.ma-chong',
  );

}